# theme: jekyll-theme-midnight
remote_theme: christianezeani/panthera-jekyll

title: Julie Hill
subtitle: Design, IT, Aspiring Programmer
description: A personal home for tech-related blogs and projects

menu:
  - text: home
    link: http://juliehill.codes
  - text: resumé
    link: http://juliehill.codes/resume
  - text: code
    link: http://juliehill.codes/code
  - text: site repo
    link: https://github.com/queenkjuul/queenkjuul.github.io
  - text: ghost town radio
    link: http://ghosttownradiosucks.com
    icon: fas fa-guitar
  - text: the melon company
    link: https://themeloncompany.bandcamp.com/releases
  - text: juliehill.rocks
    link: http://juliehill.rocks
    icon: fas fa-external-link-alt

social_icons:
  - name: GitHub
    link: https://github.com/queenkjuul
    icon: fab fa-github-square
  - name: Twitch
    link: http://twitch.tv/queenkjuul
    icon: fab fa-twitch
  - name: email
    link: mailto:julie.hill@pm.me
    icon: fas fa-envelope